[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
    https://github.com/compilerNayan/e_d_iot_core.git
build_unflags = -fno-exceptions
build_flags = -fexceptions
extra_scripts = 
	pre:scripts/generate_device_macros_pio.py	